# Generated by Django 4.0.5 on 2022-07-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='User', max_length=80, null=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
